name: CI/CD

on:
  push:
  pull_request:
  # Run daily at 0:01 UTC
  schedule:
    - cron: "1 0 * * *"

jobs:
  flake8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9s
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel poetry
          poetry install
          poetry run pip list
      - name: Lint with Flake8
        run: |
          poetry run flake8
      - name: Lint with black
        run: |
          poetry run black --check layered_edm
          poetry run black --check tests

  test:
    runs-on: ${{ matrix.os }}
    needs: flake8

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.8, 3.9, "3.10"]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel poetry
          poetry install
          poetry run pip list
      - name: Test with pytest
        run: |
          poetry run pytest -r sx
      - name: Generate code coverage
        if: github.event_name == 'push' && matrix.python-version == 3.9 && matrix.os == 'ubuntu-latest'
        run: |
          poetry run pytest --ignore=setup.py --cov=layered_edm --cov-report=term-missing --cov-report=term-missing --cov-report xml
      - name: Report coverage with Codecov
        if: github.event_name == 'push' && matrix.python-version == 3.9 && matrix.os == 'ubuntu-latest'
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          flags: unittests
